title: "Prof. Dr. Tariq Abbas | Al Qalb Darul Shifa - Multan"
description: "Cardiology Clinic in Multan. Trusted care from Prof. Dr. Tariq Abbas."
baseurl: "" 
url: "https://USERNAME.github.io/tariq-abbas-clinic" # replace USERNAME
theme: minima
